import cv2
img = cv2.imread("input1.jpg", 0)
mean = cv2.blur(img, (5, 5))
gaussian = cv2.GaussianBlur(img, (5, 5), 0)
median = cv2.medianBlur(img, 5)
cv2.imshow("output.png", img)
cv2.imshow("Mean Image", mean)
cv2.imshow("Gaussian Image", gaussian)
cv2.imshow("Median Image", median)
cv2.imwrite("output.png", img)
cv2.imwrite("output_mean.png", mean)
cv2.imwrite("output_gaussian.png", gaussian)
cv2.imwrite("output_median.png", median)
cv2.waitKey(0)
cv2.destroyAllWindows()
